dist: "trusty"
language: python
sudo: false

cache:
  apt: true

  directories:
    - $HOME/.cache/pip

python:
  - "3.5"

git:
  depth: 1

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml
      - libcups2-dev # for aeroo

      - python-dev
      - swig
      - libffi-dev
      - libssl-dev
      - python-m2crypto
      - python-httplib2
      - python3-dev

env:
  global:
  - VERSION="11.0" TESTS="0" LINT_CHECK="0"

  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"


install:
  - pip install -r requirements.txt
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly


script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
  - coverage
  - codecov
